1. Import numpy as np and see the version
Difficulty Level: L1 Q. Import numpy as `np` and print the version number.

In [2]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. How to create a boolean array?
Difficulty Level: L1 Q. Create a 3×3 numpy array of all True’s


In [3]:
ma= np.full((3,3),True)
ma

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. How to extract items that satisfy a given condition from 1D array?
Difficulty Level: L1 Q. Extract all odd numbers from arr Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired output:

#> array([1, 3, 5, 7, 9])

In [4]:
b=np.arange(0,10)
mascara=((b%2)!=0)
b[mascara]

array([1, 3, 5, 7, 9])

5. How to replace items that satisfy a condition with another value in numpy array?
Difficulty Level: L1 Q. Replace all odd numbers in arr with -1 Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired Output:

#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [5]:
c=np.arange(0,10)
c[c%2!=0]=-1
c


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6. How to replace items that satisfy a condition without affecting the original array?
Difficulty Level: L2 Q. Replace all odd numbers in arr with -1 without changing arr Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired Output:

out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
d=np.arange(10)
salida=np.where(d%2!=0,-1,d)
salida

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

7. How to reshape an array?
Difficulty Level: L1 Q. Convert a 1D array to a 2D array with 2 rows Input:
np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

In [7]:
e=np.arange(10)
e=np.reshape(e,[2,5])
e

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. How to stack two arrays vertically?
Difficulty Level: L2 Q. Stack arrays a and b vertically Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

In [23]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a,b],0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. How to stack two arrays horizontally?
Difficulty Level: L2 Q. Stack the arrays a and b horizontally. Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
Desired Output:
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [24]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a,b],1)


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. How to generate custom sequences in numpy without hardcoding?
Difficulty Level: L2 Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a. Input:

a = np.array([1,2,3])`
Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [27]:
a = np.array([1,2,3])
a=np.repeat(a,3,axis=0)
a


array([1, 1, 1, 2, 2, 2, 3, 3, 3])

11. How to get the common items between two python numpy arrays?
Difficulty Level: L2 Q. Get the common items between a and b Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Desired Output:

array([2, 4])

In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))


[2 4]


12. How to remove from one array those items that exist in another?
Difficulty Level: L2 Q. From array a remove all items present in array b Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
Desired Output:

array([1,2,3,4])

In [29]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

13. How to get the positions where elements of two arrays match?
Difficulty Level: L2 Q. Get the positions where elements of a and b match Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Desired Output:

#> (array([1, 3, 5, 7]),)

In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

14. How to extract all numbers between a given range from a numpy array?
Difficulty Level: L2 Q. Get all items between 5 and 10 from a. Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])
Desired Output:
(array([6, 9, 10]),)

In [37]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
# indice=np.where((a>=5) & (a<=10))
indice=((a>=5) & (a<=10))
a[indice]

array([ 6,  9, 10])

15. How to make a python function that handles scalars to work on numpy arrays?
Difficulty Level: L2 Q. Convert the function maxx that works on two scalars, to work on two arrays. Input:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [38]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

16. How to swap two columns in a 2d numpy array?
Difficulty Level: L2 Q. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr

In [7]:
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

17. How to swap two rows in a 2d numpy array?
Difficulty Level: L2 Q. Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)
arr

In [9]:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

18. How to reverse the rows of a 2D array?
Difficulty Level: L2 Q. Reverse the rows of a 2D array arr.

# Input
arr = np.arange(9).reshape(3,3)

In [13]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

19. How to reverse the columns of a 2D array?
Difficulty Level: L2 Q. Reverse the columns of a 2D array arr.

# Input
arr = np.arange(9).reshape(3,3)

In [27]:
arr2 = np.arange(9).reshape(3,3)
arr2[:, ::-1]





array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

20. How to create a 2D array containing random floats between 5 and 10?
Difficulty Level: L2 Q. Create a 2D array of shape 5×3 to contain random decimal numbers between 5 and 10

In [29]:
import random
array3=np.random.uniform(5,10,size=(5, 3))
array3


array([[7.58022592, 9.0452859 , 5.58684048],
       [9.81627962, 7.25999664, 7.73263841],
       [5.20762065, 8.97514895, 6.03103852],
       [8.77283582, 7.03465733, 6.90933111],
       [9.23441718, 7.45089417, 8.79962933]])

21. How to print only 3 decimal places in python numpy array?
Difficulty Level: L1 Q. Print or show only 3 decimal places of the numpy array rand_arr. Input:

In [33]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr

array([[0.687, 0.866, 0.507],
       [0.712, 0.203, 0.66 ],
       [0.816, 0.28 , 0.07 ],
       [0.203, 0.983, 0.962],
       [0.53 , 0.254, 0.788]])