In [2]:
import pandas as pd
import numpy as np


In [3]:
lista=[1,2,3,4,5,6,7,8,9]


In [4]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
matriz=[[1,2,3],[4,5,6],[7,8,9]]
matriz=np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr[0] + arr[4]

6

In [8]:
matriz[0,2]

3

In [9]:
arr[0:3] #sclicing

array([1, 2, 3])

In [11]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [12]:
arr[-1] #toma el primer valor desde el final

9

In [14]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])