In [23]:
import numpy as np

In [2]:
arra=np.array([1,2,3,4])
arra.ndim

1

In [4]:
matriz= np.array([[1,2,3],[4,5,6]])
matriz.ndim

2

In [17]:
matriz2= np.array([[[1,2,3],[4,5,6]] ,[[7,8,9],[1,11,12]]])  #3dimensiones
matriz2.ndim

3

In [26]:
v= np.array([1,2,3],ndmin=5) # define las dimensiones
print(v)


[[[[[1 2 3]]]]]


In [27]:
expand = np.expand_dims(np.array([1,2,3]),axis=0) #expande una dimension
print(expand)

[[1 2 3]]


In [29]:
v2=np.squeeze(v) #elimina dimensiones que no se estan utilizando 
print(v2)

[1 2 3]
